function [feature_list_c] = valid_project_feature_list
feature_list_c = {...
    'acc' ...
    'acp' ...
    'apd' ...
    'brp' ...
    'ctd' ...
    'dcc' ...
    'ddi' ...
    'dtd' ...
    'dsp' ...
    'evp' ...
    'hhc' ...
    'hvb' ...
    'ipu' ...
    'obc' ...
    'pmm' ...
    'ptl' ...
    'tda' ...
    'thm' ...
    'tql' ...
    'tqs' ...
    'vil' ...
    'vol' ...
    'vsc' ...
    'vsl' ...
    'vsm' ...
     };
